### ISSUE TITLE
Docker webui not working

### ISSUE THREAD

**Issue by peva3** [anttiviljami/zabbix-web-monitoring-screen#1]
Hey,

Pulling and setting up the docker image doesnt give me any errors, but when I pull up the webui chrome shows this error in the console and none of the sites are going green/red, just grey.

Uncaught TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at http://192.168.100.186:3001/client/dist/bundle.4b2bd0c0cc22e0c8d582.min.js:3:20268
    at Array.forEach (native)
    at t.<anonymous> (http://192.168.100.186:3001/client/dist/bundle.4b2bd0c0cc22e0c8d582.min.js:3:20240)
    at s (http://192.168.100.186:3001/client/dist/bundle.4b2bd0c0cc22e0c8d582.min.js:4:30264)
    at Object.fireWith [as resolveWith] (http://192.168.100.186:3001/client/dist/bundle.4b2bd0c0cc22e0c8d582.min.js:4:31035)
    at r (http://192.168.100.186:3001/client/dist/bundle.4b2bd0c0cc22e0c8d582.min.js:6:3256)
    at XMLHttpRequest.<anonymous> (http://192.168.100.186:3001/client/dist/bundle.4b2bd0c0cc22e0c8d582.min.js:6:8168)

**Comment by eddiepullen** [comment]
Hey, I would like to use this app however I am struck with the same error as mentioned by: pmwoodward3

On what Zabbix  version was this tested?
